# Generated by Django 3.1.3 on 2020-11-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Vendors',
            new_name='Vendor',
        ),
    ]
